### ISSUE TITLE
ZeroDivisionError when running with zero tests

### ISSUE THREAD

**Issue by SimonSapin** [dag/attest#109]
Attest 0.5.2 raises ZeroDivisionError when running with an empty test suite.

Test case:

```
python -c 'from attest import Tests; Tests().main()'
```

Traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../attest/collectors.py", line 241, in main
    self.run(reporter)
  File ".../attest/collectors.py", line 185, in run
    reporter.begin(self._tests)
  File ".../attest/reporters.py", line 252, in begin
    self.progress.start()
  File ".../progressbar/__init__.py", line 311, in start
    self.update(0)
  File ".../progressbar/__init__.py", line 283, in update
    self.fd.write(self._format_line() + '\r')
  File ".../progressbar/__init__.py", line 243, in _format_line
    widgets = ''.join(self._format_widgets())
  File ".../progressbar/__init__.py", line 223, in _format_widgets
    widget = format_updatable(widget, self)
  File ".../progressbar/widgets.py", line 38, in format_updatable
    if hasattr(updatable, 'update'): return updatable.update(pbar)
  File ".../progressbar/widgets.py", line 184, in update
    return '%3d%%' % pbar.percentage()
  File ".../progressbar/__init__.py", line 208, in percentage
    return self.currval * 100.0 / self.maxval
ZeroDivisionError: float division by zero
```

**Comment by dag** [comment]
Thanks for the report.
