### ISSUE TITLE
attest.run tries to use contextlib.nested in Python 3

### ISSUE THREAD

**Issue by dahlia** [dag/attest#135]
`attest.run` tries to use `contextlib.nested` which does not exist in Python 3.

``` pycon
Python 3.2.3 (default, May  3 2012, 15:51:42) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import attest.run
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "attest/__init__.py", line 5, in <module>
    from attest.collectors import *
  File "attest/collectors.py", line 5, in <module>
    from contextlib import contextmanager, nested
ImportError: cannot import name nested
```

**Comment by bradleyayers** [comment]
This is fixed in master, use that rather than 0.5.x
